### ISSUE TITLE
Watch partial files for changes

### ISSUE THREAD

**Issue by alexlafroscia** [alexlafroscia/vite-plugin-handlebars#2]
I'm not sure exactly _how_ this would work, but it would be really nice to (somehow) inform Vite of the fact that the Handlebars partials are part of the "dependency graph" of the page being viewed in the browser.

Currently, it seems like the changes are processed immediately, but the browser doesn't actually refresh in real-time.

I'm not actually sure _why_ the dev server picks up the changes to a partial without re-starting. Maybe Vite is monitoring the entire local directory? Or is just re-running the bundling step on every browser refresh? Not sure right now.

***

- [ ] Automatically trigger browser refresh when a partial changes

**Comment by jdf221** [comment]
I have a version working with partials auto reloading with new content here: https://github.com/jdf221/vite-plugin-handlebars/tree/hmr

Using Vite's built in HMR system.

Two cons though:

* If the partial is being used anywhere besides the inside of an element (ex `<div>inside here</div>`) it won't work. It's relying on two new elements being placed at the beginning and end of the inserted partial so if those elements can't be inserted and queried for it won't work.
* Any JS listeners and whatnot won't be rebound to the elements after they are reinserted. (Unless the script doing that binding is inside the partial being reloaded) Which I guess is kinda assumed/expected.

I think those were the main 2 I thought of while working on it. Both of them could be fixed by having a config option of `partialReload: "hmr" | "refresh"`. Refresh just refreshing the full page anytime a partial file is updated.

Main changes:

* Function which detects when a partial file is updated: https://github.com/jdf221/vite-plugin-handlebars/blob/hmr/src/index.ts#L58
* Those 2 surrounding elements mentioned above: https://github.com/jdf221/vite-plugin-handlebars/blob/hmr/src/partials.ts#L27
* The script injected into the client to handle the reloading (Which gets ran through microbundle and moved to dist/hmrClient.js): https://github.com/jdf221/vite-plugin-handlebars/blob/hmr/hmrClient/client.js

The whole marker elements may seem convoluted but I did it because I wan't to avoid wrapping the partial in an element since that could affect markup/JS relying on specific element nesting. Technically those 2 marker elements can be removed once the client code saves their positions but doing so makes the code much more complicated as I was doing that originally.

Will be happy to make a PR with any changes you'd recommend.

**Comment by alexlafroscia** [comment]
That's awesome @jdf221! I'd be happy to have you open the PR and we can discuss it more in that context. I have some questions but keeping that related to the specific code change might make more sense!

**Comment by evromalarkey** [comment]
Tested this today with 1.5.1 and Vite 2.2.3 and it doesn't work for me (running on windows) :/

**Comment by Batyodie** [comment]
> Tested this today with 1.5.1 and Vite 2.2.3 and it doesn't work for me (running on windows) :/

Hi, how did you solve this problem? It doesn't work for me either

**Comment by Batyodie** [comment]
@evromalarkey I found a temporary solution. You can use [vite-plugin-live-reload](https://www.npmjs.com/package/vite-plugin-live-reload) to reload individual html blocks.

vite.config.js
```js
plugins: [
    handlebars({
      reloadOnPartialChange: true,
      context: {
        title: "Hello, world!",
      },
      partialDirectory: resolve(__dirname, "src/blocks"),
    }),
    liveReload(resolve(__dirname, "src/blocks/**/*"), { alwaysReload: true }),
  ],
```
